#!/bin/bash
#
# Cpu Usage
#
# user      nice  system  idle      iowait  irq   softirq   steal   guest   guest_nice
# $2        $3    $4      $5        $6      $7    $8        $9      $10     $11
# 10257396  43821 3221028 130740590 24937   0     137500    0       0       0

LAST_STAT=/tmp/last_cpu_stat
CURRENT_STAT=/proc/stat

[[ ! -f "${LAST_STAT}" ]] && < ${CURRENT_STAT} tee ${LAST_STAT}

{ cat ${LAST_STAT} && < ${CURRENT_STAT} tee $LAST_STAT; } | awk '/^cpu / {usr=$2-usr; sys=$4-sys; idle=$5-idle; iow=$6-iow} END {total=usr+sys+idle+iow; printf "%.1f%", (total-idle)*100/total}'
